services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    port: 5678
    envVars:
      - key: N8N_HOST
        value: n8n-h0nj.onrender.com
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-h0nj.onrender.com
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: securepassword
      - key: N8N_PORT
        value: 5678
      - key: GENERIC_TIMEZONE
        value: Europe/Paris
